// top and left numbers are the % percentage of the image dimensions

const gamingPc: PC = {
  case: {
    name: 'NZXT H510 (R6 Siege Limited Edition)',
    image: 'https://m.media-amazon.com/images/I/519V7JLYZEL._AC_SL1000_.jpg',
    url: 'https://www.amazon.com/dp/B07TD9C5HS',
    asin: 'B07TD9C5HS',
    top: 1,
    left: 6,
    icon: 'desktop-tower',
  },
  cpu: {
    name: 'Intel Core i9-10900K',
    image: 'https://m.media-amazon.com/images/I/71f0lWEgQNL._AC_SL1500_.jpg',
    url: 'https://amzn.to/3lljJsz',
    asin: 'B08H2DRCWZ',
    top: 26,
    left: 38,
    icon: 'memory',
  },
  cooler: {
    name: 'NZXT Kraken Z63 AIO Liquid Cooler',
    image: 'https://m.media-amazon.com/images/I/71TvN0tgWjL._AC_SL1500_.jpg',
    url: 'https://amzn.to/38wSRC4',
    asin: 'B082DYSQVF',
    top: 37,
    left: 89,
    icon: 'fan',
  },
  motherboard: {
    name: '',
    image: '',
    url: '',
    asin: '',
    top: 14,
    left: 22,
    icon: 'raspberry-pi',
  },
  memory: {
    name: 'G.SKILL Trident Z Royal RGB 32GB',
    image: 'https://m.media-amazon.com/images/I/71UzA2UD9rL._AC_SL1300_.jpg',
    url: 'https://amzn.to/3ndzkL4',
    asin: 'B07N7SBSF4',
    top: 20,
    left: 55,
    icon: 'train-car-container',
  },
  storage: [
    {
      name: 'Samsung 970 EVO Plus 1TB M.2 Drive',
      image: 'https://m.media-amazon.com/images/I/71OYNmVRFhL._AC_SL1500_.jpg',
      url: 'https://amzn.to/3eQQpYj',
      asin: 'B07MFZY2F2',
      top: 65,
      left: 30,
      icon: 'harddisk',
    },
    {
      name: 'Samsung 970 EVO Plus 2TB M.2 Drive',
      image: 'https://m.media-amazon.com/images/I/61QFPk2HBmL._AC_SL1001_.jpg',
      url: 'https://amzn.to/35fXdvr',
      asin: 'B07MFZXR1B',
      top: 65,
      left: 48,
      icon: 'harddisk',
    },
  ],
  gpu: {
    name: 'NVIDIA GeForce RTX 3080',
    image: 'https://m.media-amazon.com/images/I/61juKdIql1L._AC_SL1500_.jpg',
    url: 'https://amzn.to/3kl8BdG',
    asin: 'B08JCRHZGW',
    top: 50,
    left: 38,
    icon: 'expansion-card',
  },
  psu: {
    name: 'NZXT C1000 Gold',
    image: 'https://m.media-amazon.com/images/I/51nrWKGjFwL._AC_SL1000_.jpg',
    url: 'https://www.amazon.com/dp/B09YZ33Z46',
    asin: 'B09YZ33Z46',
    top: 81,
    left: 13,
    icon: 'power-plug',
  },
  other: [],
};

export default gamingPc;
