const gamingPc: PC = {
  case: {
    name: 'NZXT H510 (R6 Siege Limited Edition)',
    image: '',
    url: 'https://www.amazon.com/dp/B07TD9C5HS',
    posX: 200,
    posY: 300,
    height: 100,
  },
  cpu: {
    name: 'Intel Core i9-10900K',
    image: '',
    url: 'https://amzn.to/3lljJsz',
    posX: 200,
    posY: 300,
    height: 100,
  },
  cooler: {
    name: 'NZXT Kraken Z63 AIO Liquid Cooler',
    image: '',
    url: 'https://amzn.to/38wSRC4',
    posX: 200,
    posY: 300,
    height: 100,
  },
  motherboard: {
    name: '',
    image: '',
    url: '',
    posX: 200,
    posY: 300,
    height: 100,
  },
  memory: {
    name: 'G.SKILL Trident Z Royal RGB 32GB',
    image: '',
    url: 'https://amzn.to/3ndzkL4',
    posX: 200,
    posY: 300,
    height: 100,
  },
  storage: [
    {
      name: 'Samsung 970 EVO Plus 1TB M.2 Drive',
      image: '',
      url: 'https://amzn.to/3eQQpYj',
      posX: 200,
      posY: 300,
      height: 100,
    },
    {
      name: 'Samsung 970 EVO Plus 2TB M.2 Drive',
      image: '',
      url: 'https://amzn.to/35fXdvr',
      posX: 200,
      posY: 300,
      height: 100,
    },
  ],
  gpu: {
    name: 'NVIDIA GeForce RTX 3080',
    image: '',
    url: 'https://amzn.to/3kl8BdG',
    posX: 200,
    posY: 300,
    height: 100,
  },
  psu: {
    name: 'NZXT C1000 Gold',
    image: '',
    url: 'https://www.amazon.com/dp/B09YZ33Z46',
    posX: 200,
    posY: 300,
    height: 100,
  },
  other: [],
};

export default gamingPc;
