const peripherals: { [key: string]: Item } = {
  monitor: {
    name: 'Samsung Odyssey G7 27"',
    image: '',
    url: 'https://amzn.to/32yois3',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  keyboard: {
    name: 'Logitech G Pro X',
    image: '',
    url: 'https://amzn.to/39gLkq4',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  mouse: {
    name: 'Logitech G Pro Wireless',
    image: '',
    url: 'https://amzn.to/35ojO8T',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  headset: {
    name: 'Logitech G Pro X Headset',
    image: '',
    url: 'https://amzn.to/3q75gST',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  camera: {
    name: 'Sony α7 III',
    image: '',
    url: 'https://amzn.to/30uCioS',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  cameraLens: {
    name: 'Canon EF 16-35mm f/4L',
    image: '',
    url: 'https://amzn.to/38sw4HP',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  microphone: {
    name: 'Blue Microphones Blackout Spark SL',
    image: '',
    url: 'https://amzn.to/2UcE2MT',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  dac: {
    name: 'Native Instruments Komplete Audio 6 Mk2',
    image: '',
    url: 'https://amzn.to/3s8D4TX',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  compressor: {
    name: 'DBX 266xs',
    image: '',
    url: 'https://amzn.to/2uHNme5',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  streamDeck: {
    name: 'Elgato Stream Deck XL',
    image: '',
    url: 'https://amzn.to/2QYNORO',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
  speakers: {
    name: 'PreSonus Eris E3.5',
    image: '',
    url: 'https://amzn.to/2YKlDXR',
    asin: '',
    top: 300,
    left: 200,
    icon: '',
  },
};

export default peripherals;
