// top and left numbers are the % percentage of the image dimensions

const streamingPc: PC = {
  case: {
    name: 'SilverStone RM44',
    image: 'https://m.media-amazon.com/images/I/71WEd+yCYbL._AC_SL1500_.jpg',
    url: 'https://www.amazon.com/dp/B0BFC8FZ8B',
    asin: 'B0BFC8FZ8B',
    top: 64,
    left: 6.1,
    icon: 'desktop-tower',
  },
  cpu: {
    name: 'AMD Ryzen 9 3950X',
    image: 'https://m.media-amazon.com/images/I/7122uH4-hfL._AC_SL1121_.jpg',
    url: 'https://amzn.to/371xQMt',
    asin: 'B07ZTYKLZW',
    top: 46.1,
    left: 38.1,
    icon: 'memory',
  },
  cooler: {
    name: 'NZXT Kraken X63 AIO Liquid Cooler',
    image: 'https://m.media-amazon.com/images/I/71dlZ0vqmxL._SL1500_.jpg',
    url: 'https://amzn.to/2FwPK15',
    asin: 'B09GKQ4KYP',
    top: 14,
    left: 84.8,
    icon: 'fan',
  },
  motherboard: {
    name: 'ASUS ROG Strix X570 Crosshair VIII Hero',
    image: 'https://m.media-amazon.com/images/I/61-7KxpmIEL._AC_SL1000_.jpg',
    url: 'https://amzn.to/3ku4CfF',
    asin: 'B07SZXBTNW',
    top: 34,
    left: 26.7,
    icon: 'raspberry-pi',
  },
  memory: {
    name: 'Corsair Vengeance RGB Pro (4x16GB)',
    image: 'https://m.media-amazon.com/images/I/81PIk2a8YZL._AC_SL1500_.jpg',
    url: 'https://www.amazon.com/dp/B08GSSY4J4',
    asin: 'B08GSSY4J4',
    top: 32.5,
    left: 47,
    icon: 'train-car-container',
  },
  storage: [
    {
      name: 'Intel Optane 905p 960GB SSD',
      image: 'https://m.media-amazon.com/images/I/71D8j04M2GL._AC_SL1280_.jpg',
      url: 'https://www.amazon.com/dp/B0772XB3MY',
      asin: 'B0772XB3MY',
      top: 91,
      left: 47.8,
      icon: 'harddisk',
    },
    {
      name: 'Seagate Barracuda Pro 10TB HDD',
      image: 'https://m.media-amazon.com/images/I/71DmtkEDt5L._AC_SL1500_.jpg',
      url: 'https://amzn.to/2QLsmhd',
      asin: 'B01IA9H22Q',
      top: 45.5,
      left: 53.3,
      icon: 'harddisk',
    },
  ],
  gpu: {
    name: 'Gigabyte Geforce RTX 2080 Ti Turbo',
    image: 'https://m.media-amazon.com/images/I/71QYE3w6zPL._AC_SL1500_.jpg',
    url: 'https://amzn.to/32sccB0',
    asin: 'B083DT8Q9L',
    top: 69.4,
    left: 24.3,
    icon: 'expansion-card',
  },
  psu: {
    name: 'NZXT C1000 Gold',
    image: 'https://m.media-amazon.com/images/I/51nrWKGjFwL._AC_SL1000_.jpg',
    url: 'https://www.amazon.com/dp/B09YZ33Z46',
    asin: 'B09YZ33Z46',
    top: 13,
    left: 18,
    icon: 'power-plug',
  },
  other: [
    {
      name: 'Elgato Game Capture 4K60 Pro',
      image: 'https://m.media-amazon.com/images/I/61KnGI5sUgL._AC_SL1500_.jpg',
      url: 'https://amzn.to/2xUxGJR',
      asin: 'B076ZQBN6R',
      top: 82.4,
      left: 25.6,
      icon: 'expansion-card',
    },
    {
      name: 'Elgato Game Capture HD60 Pro',
      image: 'https://m.media-amazon.com/images/I/71D7tnwLm-L._AC_SL1500_.jpg',
      url: 'https://amzn.to/2xGWe8O',
      asin: 'B015E3OT54',
      top: 82.4,
      left: 30,
      icon: 'expansion-card',
    },
    {
      name: 'Noctua NF-P12 redux-1700 PWM',
      image: 'https://m.media-amazon.com/images/I/81ZUUX5VZsL._AC_SL1500_.jpg',
      url: 'https://www.amazon.com/dp/B07CG2PGY6',
      asin: 'B07CG2PGY6',
      top: 48.8,
      left: 80.3,
      icon: 'fan',
    },
  ],
};

export default streamingPc;
